services:
  - type: web
    name: travelrn-api
    env: docker
    plan: free
    region: oregon
    dockerfilePath: backend/Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: travelrn-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: travelrn-redis
          type: redis
          property: connectionString
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      # Partner API URL/KEYs can be added in the Render dashboard as env vars
    healthCheckPath: /health

  - type: worker
    name: travelrn-worker
    env: docker
    plan: free
    region: oregon
    dockerfilePath: backend/Dockerfile
    startCommand: celery -A app.tasks.celery_app worker --loglevel=INFO
    envVars:
      - key: APP_ENV
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: travelrn-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: travelrn-redis
          type: redis
          property: connectionString

  - type: worker
    name: travelrn-beat
    env: docker
    plan: free
    region: oregon
    dockerfilePath: backend/Dockerfile
    startCommand: celery -A app.tasks.celery_app beat --loglevel=INFO
    envVars:
      - key: APP_ENV
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: travelrn-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: travelrn-redis
          type: redis
          property: connectionString

databases:
  - name: travelrn-db
    plan: free
    region: oregon

redis:
  - name: travelrn-redis
    plan: free
    region: oregon
